/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        tanvoBg: '#F8EDED',
        tanvoPrimary: '#B43F3F',
        tanvoAccent: '#FF8225',
        tanvoDark: '#173B45',
        // Phase 4 Redesign Colors
        "primary": "#93272a",
        "secondary": "#775a19",
        "background": "#fbf9f4",
        "surface-container": "#f0eee9",
        "surface-container-low": "#f5f3ee",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1c19",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#574140",
        "outline-variant": "#debfbd",
        "secondary-container": "#fed488",
        "on-secondary-container": "#785a1a",
        "tertiary-container": "#686767",
        "on-primary-fixed": "#410005",
        "surface-dim": "#dbdad5",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-tint": "#a83637",
        "on-tertiary-container": "#e9e6e6",
        "primary-fixed": "#ffdad7",
        "inverse-on-surface": "#f2f1ec",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e2dd",
        "surface": "#fbf9f4",
        "on-secondary-fixed-variant": "#5d4201",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#ffb3af",
        "primary-container": "#b43f3f",
        "on-primary-container": "#ffe0dd",
        "surface-variant": "#e4e2dd",
        "surface-container-high": "#eae8e3",
        "inverse-surface": "#30312e",
        "outline": "#8b716f",
        "on-tertiary-fixed": "#1c1b1b",
        "inverse-primary": "#ffb3af",
        "on-primary-fixed-variant": "#871e22",
        "secondary-fixed": "#ffdea5",
        "surface-bright": "#fbf9f4",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#e9c176",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#474746",
        "on-secondary-fixed": "#261900",
        "tertiary": "#504f4f",
        "tanvo-raw-cotton": "#F9F5EE",
        "tanvo-madder-red": "#780000",
        "tanvo-charcoal": "#0D0B0A"
      },
      spacing: {
        "section-gap": "120px",
        "margin-edge": "48px",
        "container-max": "1440px",
        "gutter": "32px",
        "unit": "10px"
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "160%", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "130%", "letterSpacing": "0em", "fontWeight": "700"}],
        "headline-lg": ["48px", {"lineHeight": "120%", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "120%", "letterSpacing": "0.2em", "fontWeight": "700"}],
        "display-xl": ["84px", {"lineHeight": "110%", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "165%", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "display-xl-mobile": ["56px", {"lineHeight": "110%", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      fontFamily: {
        serif: ['Playfair Display', 'serif'],
        sans: ['Montserrat', 'sans-serif'],
        headline: ['Noto Serif', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        "body-lg": ["Raleway"],
        "headline-md": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "label-sm": ["Inter"],
        "display-xl": ["Playfair Display"],
        "body-md": ["Raleway"],
        "display-xl-mobile": ["Playfair Display"]
      },
    },
  },
  plugins: [],
}

