/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        tanvoBg: '#F8EDED',
        tanvoPrimary: '#B43F3F',
        tanvoAccent: '#FF8225',
        tanvoDark: '#173B45',
        // Phase 4 Redesign Colors
        "primary": "#93272a",
        "secondary": "#775a19",
        "background": "#fbf9f4",
        "surface-container": "#f0eee9",
        "surface-container-low": "#f5f3ee",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1c19",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#574140",
        "outline-variant": "#debfbd",
        "secondary-container": "#fed488",
        "on-secondary-container": "#785a1a",
        "tertiary-container": "#686767",
        "on-primary-fixed": "#410005",
        "surface-dim": "#dbdad5",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-tint": "#a83637",
        "on-tertiary-container": "#e9e6e6",
        "primary-fixed": "#ffdad7",
        "inverse-on-surface": "#f2f1ec",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e2dd",
        "surface": "#fbf9f4",
        "on-secondary-fixed-variant": "#5d4201",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#ffb3af",
        "primary-container": "#b43f3f",
        "on-primary-container": "#ffe0dd",
        "surface-variant": "#e4e2dd",
        "surface-container-high": "#eae8e3",
        "inverse-surface": "#30312e",
        "outline": "#8b716f",
        "on-tertiary-fixed": "#1c1b1b",
        "inverse-primary": "#ffb3af",
        "on-primary-fixed-variant": "#871e22",
        "secondary-fixed": "#ffdea5",
        "surface-bright": "#fbf9f4",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#e9c176",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#474746",
        "on-secondary-fixed": "#261900",
        "tertiary": "#504f4f",
      },
      fontFamily: {
        serif: ['Playfair Display', 'serif'],
        sans: ['Montserrat', 'sans-serif'],
        headline: ['Noto Serif', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

